travis:
  secure:
    BINSTAR_TOKEN: jQ2W+EVuv34VW6tQKHiIs8Zl1LRqXeEQGbq+kSfXtrDHBZA6PEg8GB0VOZsT50yM+nLqnaLcBCCGd58R54C1eyZ0OcrZZXNg+qbMM9z0TvfyVxQnkTzdDpfN8CHPtX9GXBo8TAYD3mLbAHq1FajJl/7o1YrInPTcu173IBIKEfBHHfoyTho3Ta9j9vkmS/ecXWbsy9MqxfaFnRkAFx8ha9DZ9UVYto3Xyzua/VwYRY+FoBiNEbh8g70U8+XUAKKs7kL3oJyQclHxT0WNBXqTVjq57DesFeIsGD7zQd3tVCxm3ow4wc2pgmBoWEuPRRAKisbGn1EL44NtEO+UPQyi2luj2T8GDNO5522V4FfYLd2+Ftgwzu2kUXgX+xLfMOAGYcHnB4KmPfkgPoK3bC8hI+Xqm4Rs++gfsGvk5miOXKl19Jpci3XOGmZYnJuqtbmjNFVD/b5V7uTnch0Tl2DO8en6xn3pHkP3IgV7CD0FfkaMHtLtJv+9hhR1ljvomtnrQrpqKJxvkDYcBNE/+xq1kLUwTHakhbXveZ78itoG0ofi2sBBOWjbOM8lOcUhUqas/+NZmDGDxiCMM0NohSU/C78Mjjao+fQuDyAt01jMaI9G90LqlKWN0WylhU2e+3bsFAKQ98LLmzgbWqEOmOIYi4RRfkNFVJ7dN+oxY30PPsU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
