travis:
  secure:
    BINSTAR_TOKEN: CDI3CMOs+wLIsZ5rO9oR/dfoRFE5Ir35Zd0eexqXJvGuvOG3qugbbz8+Ndd6mjVvwm+ox8SJH8EuYaxAmpNYotiIYPZyCPS38AOOXx3f+J4SdMODTZkAj9w31o8hhdrnymAktK8OuKbf7qU1S0trSjF4xZGpcZIVg0YGLl+UbY+4NIsLGWC65Ew3pRPY4Gy7x59HEzfQti1azdBnn32Uh2pZYF82lmeHW1o6jdQ+67dJuoP3jTN1RWu1Na6jyt9PaqDzDdL+9OA33WkOkUah/j0CaXQgJkeMKPzmQjmHxWUK9mV3CeV2+g94+VpNEAveVl/lElutJ2S4D5cghGjBam6R43pXpkj4hTh1CBWd6EXF1N2DlMCaBo2jF1+gvmF9c5Y/O3yArlm4gmrUpHtdx7PD2IKtPiu7U4T830Zivajox9LPjOEyz4Tfn8z97qXP1i2w4bOiwRxHjxuCyohZ/KxR4yAFQgP8j0CvzGNzcPp0u0M3Eop6GtF5km1KYPXLq0gREVgDW5CiZFSJFcWRly6Q7h/huPorKBVz8C0ePRO0aBtfSHhxq9+bt5Kl+0ECzqAiFWI8IQn4LZ1QSSkdLekyZp46Ilv2pb6bMdmGcYmh0rOb0u8/dn3iQsdcfYpHzkX+SfvsYNP4gPE9A2Ym2mIFs+rIPoitSqKqGMC/mC0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
